apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hw23-developer-pod-reader
  namespace: hw23
subjects:
  - kind: User
    name: developer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hw23-pod-reader
